# Generated by Django 5.1.6 on 2025-03-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rose", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
