# Generated by Django 5.1.6 on 2025-03-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rose", "0002_alter_appointment_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="preffered_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="preffered_time",
            new_name="time",
        ),
    ]
